---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: my-cockroach-release
  namespace: flux-cockroach
spec:
  chart:
    spec:
      chart: cockroachdb
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: cockroach-repository
      version: '>10.0.0'
  interval: 5m0s
  targetNamespace: flux-cockroach
